{"content": {"suites": {"0": {"status": {"total_pass": 1, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_product_creation", "rerun": "0"}}, "suite_name": "backend/tests/api/test_products.py"}, "1": {"suite_name": "backend/tests/api/test_user.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_user_create", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_set_check_password", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_register_user", "rerun": "0"}}, "status": {"total_pass": 3, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "2": {"suite_name": "backend/tests/unit/test_unit.py", "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_product_model", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_review_model", "rerun": "0"}, "2": {"status": "PASS", "message": "", "test_name": "test_order_model", "rerun": "0"}, "3": {"status": "PASS", "message": "", "test_name": "test_order_item_model", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_shipping_address_model", "rerun": "0"}}, "status": {"total_pass": 5, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 0, "total_error": 0}}, "3": {"suite_name": "backend/tests/api/test_products.py", "tests": {"0": {"status": "FAIL", "message": "   assert 401 == 200\n    +  where 401 = <Response status_code=401, \"application/json\">.status_code\n", "test_name": "test_api_product_creation", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 0}}, "4": {"suite_name": "backend/tests/e2e/test_e2e.py", "tests": {"0": {"status": "FAIL", "message": "   selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\".col-xl-3:nth-child(2) strong\"}\n     (Session info: chrome=131.0.6778.265); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\n   Stacktrace:\n   \tGetHandleVerifier [0x00007FF6C1F980D5+2992373]\n   \t(No symbol) [0x00007FF6C1C2BFD0]\n   \t(No symbol) [0x00007FF6C1AC590A]\n   \t(No symbol) [0x00007FF6C1B1926E]\n   \t(No symbol) [0x00007FF6C1B1955C]\n   \t(No symbol) [0x00007FF6C1B627D7]\n   \t(No symbol) [0x00007FF6C1B3F3AF]\n   \t(No symbol) [0x00007FF6C1B5F584]\n   \t(No symbol) [0x00007FF6C1B3F113]\n   \t(No symbol) [0x00007FF6C1B0A918]\n   \t(No symbol) [0x00007FF6C1B0BA81]\n   \tGetHandleVerifier [0x00007FF6C1FF6A2D+3379789]\n   \tGetHandleVerifier [0x00007FF6C200C32D+3468109]\n   \tGetHandleVerifier [0x00007FF6C2000043+3418211]\n   \tGetHandleVerifier [0x00007FF6C1D8C78B+847787]\n   \t(No symbol) [0x00007FF6C1C3757F]\n   \t(No symbol) [0x00007FF6C1C32FC4]\n   \t(No symbol) [0x00007FF6C1C3315D]\n   \t(No symbol) [0x00007FF6C1C22979]\n   \tBaseThreadInitThunk [0x00007FFE97AA259D+29]\n   \tRtlUserThreadStart [0x00007FFE989EAF38+40]\n", "test_name": "test_search_button", "rerun": "0"}, "1": {"status": "ERROR", "message": "file C:\\Users\\Ayat Abu Galion\\OneDrive\\Desktop\\FinalProject\\final-project\\backend\\tests\\e2e\\test_e2e.py, line 31\n  def test_login(self):\nE       fixture 'self' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, db, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, extra, extras, include_metadata_in_junit_xml, live_server, mailoutbox, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\Ayat Abu Galion\\OneDrive\\Desktop\\FinalProject\\final-project\\backend\\tests\\e2e\\test_e2e.py:31\n", "test_name": "test_login", "rerun": "0"}, "2": {"status": "ERROR", "message": "file C:\\Users\\Ayat Abu Galion\\OneDrive\\Desktop\\FinalProject\\final-project\\backend\\tests\\e2e\\test_e2e.py, line 51\n  def test_order_summary(self):\nE       fixture 'self' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, db, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, extra, extras, include_metadata_in_junit_xml, live_server, mailoutbox, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\Ayat Abu Galion\\OneDrive\\Desktop\\FinalProject\\final-project\\backend\\tests\\e2e\\test_e2e.py:51\n", "test_name": "test_order_summary", "rerun": "0"}, "3": {"status": "ERROR", "message": "file C:\\Users\\Ayat Abu Galion\\OneDrive\\Desktop\\FinalProject\\final-project\\backend\\tests\\e2e\\test_e2e.py, line 70\n  def test_navigation_back_to_homepg(self):\nE       fixture 'self' not found\n>       available fixtures: _dj_autoclear_mailbox, _django_clear_site_cache, _django_db_helper, _django_db_marker, _django_set_urlconf, _django_setup_unittest, _fail_for_invalid_template_variable, _live_server_helper, _template_string_if_invalid_marker, admin_client, admin_user, async_client, async_rf, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, client, db, django_assert_max_num_queries, django_assert_num_queries, django_capture_on_commit_callbacks, django_db_blocker, django_db_createdb, django_db_keepdb, django_db_modify_db_settings, django_db_modify_db_settings_parallel_suffix, django_db_modify_db_settings_tox_suffix, django_db_modify_db_settings_xdist_suffix, django_db_reset_sequences, django_db_serialized_rollback, django_db_setup, django_db_use_migrations, django_mail_dnsname, django_mail_patch_dns, django_test_environment, django_user_model, django_username_field, doctest_namespace, extra, extras, include_metadata_in_junit_xml, live_server, mailoutbox, metadata, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, rf, settings, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, transactional_db\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\Ayat Abu Galion\\OneDrive\\Desktop\\FinalProject\\final-project\\backend\\tests\\e2e\\test_e2e.py:70\n", "test_name": "test_navigation_back_to_homepg", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 1, "total_error": 3}}, "5": {"suite_name": "backend/tests/integration/test_integration.py", "tests": {"0": {"status": "FAIL", "message": "       TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'\n       django.core.paginator.PageNotAnInteger: That page number is not an integer\n   RuntimeError: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\n", "test_name": "test_api_product_list", "rerun": "0"}, "1": {"status": "FAIL", "message": "   RuntimeError: Database access not allowed, use the \"django_db\" mark, or the \"db\" or \"transactional_db\" fixtures to enable it.\n", "test_name": "test_api_product_retrieve", "rerun": "0"}, "2": {"status": "FAIL", "message": "   assert 405 == 200\n    +  where 405 = <Response status_code=405, \"application/json\">.status_code\n", "test_name": "test_api_product_update", "rerun": "0"}, "3": {"status": "FAIL", "message": "   assert 405 == 204\n    +  where 405 = <Response status_code=405, \"application/json\">.status_code\n", "test_name": "test_api_product_delete", "rerun": "0"}, "4": {"status": "FAIL", "message": "   assert 401 == 400\n    +  where 401 = <Response status_code=401, \"application/json\">.status_code\n", "test_name": "test_api_product_creation_invalid", "rerun": "0"}}, "status": {"total_pass": 0, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 5, "total_error": 0}}}}, "date": "January 11, 2025", "start_time": 1736606454.3012595, "total_suite": 6, "status": "FAIL", "status_list": {"pass": "9", "fail": "7", "skip": "0", "error": "3", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "19"}